### ISSUE TITLE
Identify and throw specific error codes/messages

### ISSUE THREAD

**Issue by itsgaryk** [AnotherCat/message-bot#19]
**Is your feature request related to a problem? Please describe.**
Yes and no

**Describe the solution you'd like**
Currently the bot throws the following generic error message:

"There was an unknown error! This has been reported to the devs.
If by any chance this broke something, contact us through our support server"

When entering an incorrect command the bot should evaluate the message and determine the issue.

For example: 
If the first parameter in an edit/delete command contains an invalid channel ID
If the second parameter in an edit/delete command contains an invalid message ID

**Describe alternatives you've considered**
No alternatives

**Additional context**
None I can think of

**Comment by quirky-bluejay** [comment]
The way i've set up error handling is that it will check for specific cases i've already specified, and then throw the generic one if not.
I have tried to think up all possible scenarios and combinations, but i can't think of all of them.

What was the exact command usage or series of command usage?
And if id's were used, which ones were wrong?

I'll try and reproduce this, then push an addition to the error handlers.

**Comment by itsgaryk** [comment]
Here's an example: Sometimes I accidentally mix the channel ID with the message ID when using !edit and it throws a generic error.

Channel ID example: 111111
Message ID example: 222222

So instead of
!edit message 11111 2222

I write 
!edit message 2222 1111

It throws the generic error message

**Comment by quirky-bluejay** [comment]
@itsgaryk 
Do you mind testing it again?

I've tested it but there might be something i've missed.
