### ISSUE TITLE
Auto delete usage of commands

### ISSUE THREAD

**Issue by quirky-bluejay** [AnotherCat/message-bot#37]
**Describe the solution you'd like**
When a message command is used delete it's usage (eg `~send #bot hiii :wave:`) and leave the embed saying it's sent
This would be enabled in a server specific setting

**Describe alternatives you've considered**
Leave it how it is

**Additional context**
This issue was made in response to a feature request in the support server by `Stimmicus#7588`.
[Here](https://discord.com/channels/742373263593963614/765829727003869194/792079709097558036) is the message link

- [x] Figure it out
- [ ] #81

**Comment by Cronosus** [comment]
i agree... 
just few adjustments, to delete all messages from bot and also messages that are reply or command for bot.
like when i send just ~send and bot then ask for id etc, so make it delete even those replies
and also command to setup delay for deleting messages
~setup delay [time in seconds]

**Comment by quirky-bluejay** [comment]
Hi! @Cronosus 
The system has moved on from here I'm afraid, moving to discord interactions. That means that this isn't relevant anymore, as now command usage will only be visible to the user invoking the command!
This system is set to roll out sometime during this month. 
Here's the announcement on the support server regarding that:
![image](https://user-images.githubusercontent.com/52091960/174272426-562dc814-210a-45c2-8121-adc6cdf8f494.png)

And I encourage you to join our [support server](https://discord.gg/xFZu29t) to stay in the loop!
